/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Model.GachaSystem;
import Model.PullHistory;
import java.awt.Color;
import java.util.List;
import javax.swing.JLabel;


public class HistoryDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HistoryDialog.class.getName());
    
    public HistoryDialog(java.awt.Frame parent, boolean modal, GachaSystem gachaSystem) {
        super(parent, modal);
        initComponents();
        
        List<PullHistory> histories = gachaSystem.getPoolHistory();
        
        for(PullHistory h : histories){
            JLabel lbl = new JLabel();
            lbl.setText("#" + h.getPullNumber() + " - " + h.getItem().toString());
            lbl.setForeground(Color.white);
            mainPanel.add(lbl,0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContainer = new javax.swing.JPanel();
        panelTittle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        footerPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("History");
        setPreferredSize(new java.awt.Dimension(200, 300));

        panelContainer.setLayout(new java.awt.BorderLayout());

        panelTittle.setBackground(new java.awt.Color(170, 11, 11));
        panelTittle.setPreferredSize(new java.awt.Dimension(200, 40));
        panelTittle.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("History");
        panelTittle.add(jLabel1, new java.awt.GridBagConstraints());

        panelContainer.add(panelTittle, java.awt.BorderLayout.PAGE_START);

        mainPanel.setBackground(new java.awt.Color(0, 0, 0));
        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 1, 1));
        mainPanel.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(mainPanel);

        panelContainer.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        footerPanel.setBackground(new java.awt.Color(170, 11, 11));
        footerPanel.setPreferredSize(new java.awt.Dimension(10, 25));
        footerPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(170, 11, 11));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnClose.setBackground(new java.awt.Color(170, 11, 11));
        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("close");
        btnClose.setBorderPainted(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setFocusPainted(false);
        btnClose.addActionListener(this::btnCloseActionPerformed);
        jPanel1.add(btnClose, new java.awt.GridBagConstraints());

        footerPanel.add(jPanel1, java.awt.BorderLayout.EAST);

        panelContainer.add(footerPanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(panelContainer, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(300, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelContainer;
    private javax.swing.JPanel panelTittle;
    // End of variables declaration//GEN-END:variables
}
