package View;

import Model.Item;
import Model.Player;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class InventoryDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InventoryDialog.class.getName());

    public InventoryDialog(java.awt.Frame parent, boolean modal, List<Item> inventory) {
        super(parent, modal);
        initComponents();
        int s3Obtained = 0;
        int s4Obtained = 0;
        int s5Obtained = 0;

        setUndecorated(true);
        setBackground(new Color(0, 0, 0, 0));
        jScrollPane1.getViewport().setOpaque(false);
        containerCenter.setBackground(new Color(0, 0, 0, 180));

        Map<String, Integer> itemCount = new HashMap();
        Map<String, Item> itemData = new HashMap();

        for (Item item : inventory) {

            switch (item.getRarity()) {
                case 3:
                    s3Obtained++;
                    break;
                case 4:
                    s4Obtained++;
                    break;
                case 5:
                    s5Obtained++;
                    break;
                default:
                    System.out.println("ini tidak akan dijalankan");
                    break;
            }

            itemCount.put(item.getName(), itemCount.getOrDefault(item.getName(), 0) + 1);

            itemData.put(item.getName(), item);
        }

        List<Item> sortedItems = new ArrayList<>(itemData.values());

        sortedItems.sort((a, b) -> Integer.compare(b.getRarity(), a.getRarity()));

        for (Item item : sortedItems) {

           int jumlah = itemCount.get(item.getName());

    // 1. Buat kontainer kartu dasar
    JPanel card = new JPanel();
    card.setBackground(Color.WHITE);
    card.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    card.setLayout(new BorderLayout());

    // 2. Gunakan CharacterDisplayPanel buatanmu untuk menampilkan gambar secara tajam
    CharacterDisplayPanel panelGambarKarakter = new CharacterDisplayPanel(item.getImagePath());
    
    // Set ukuran area gambar di dalam kartu agar proporsional
    panelGambarKarakter.setPreferredSize(new Dimension(180, 220)); 

    // 3. Buat label informasi jumlah item yang dimiliki
    JLabel lblJumlah = new JLabel("Owned : " + jumlah, JLabel.CENTER);
    lblJumlah.setFont(new java.awt.Font("Segoe UI", 1, 12));

    // 4. Masukkan panel gambar tajam dan label ke dalam kartu
    card.add(panelGambarKarakter, BorderLayout.CENTER);
    card.add(lblJumlah, BorderLayout.SOUTH);

    // Set ukuran total kontainer kartu inventory
    card.setPreferredSize(new Dimension(180, 260));

    // 5. Masukkan kartu ke dalam kontainer utama halaman inventory
    panelItemsContainer.add(card);
        }

        lblS3Obtained.setText("Obtained : " + s3Obtained);
        lblS4Obtained.setText("Obtained : " + s4Obtained);
        lblS5Obtained.setText("Obtained : " + s5Obtained);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        topPanel = new javax.swing.JPanel();
        closePanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();
        panelJudul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        containerCenter = new javax.swing.JPanel();
        panelInfoRarityObtained = new javax.swing.JPanel();
        star3InfoPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblS3Obtained = new javax.swing.JLabel();
        star4InfoPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblS4Obtained = new javax.swing.JLabel();
        star5InfoPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblS5Obtained = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelItemsContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventory");
        setPreferredSize(new java.awt.Dimension(1024, 576));

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setPreferredSize(new java.awt.Dimension(689, 45));
        topPanel.setLayout(new java.awt.BorderLayout());

        closePanel.setOpaque(false);
        closePanel.setPreferredSize(new java.awt.Dimension(45, 45));
        closePanel.setLayout(new java.awt.GridBagLayout());

        jButton1.setBackground(new java.awt.Color(170, 11, 11));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/close.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        closePanel.add(jButton1, new java.awt.GridBagConstraints());

        topPanel.add(closePanel, java.awt.BorderLayout.EAST);

        panel1.setOpaque(false);
        panel1.setPreferredSize(new java.awt.Dimension(45, 45));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        topPanel.add(panel1, java.awt.BorderLayout.WEST);

        panelJudul.setOpaque(false);
        panelJudul.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Inventory");
        panelJudul.add(jLabel1, new java.awt.GridBagConstraints());

        topPanel.add(panelJudul, java.awt.BorderLayout.CENTER);

        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);

        containerCenter.setLayout(new java.awt.BorderLayout());

        panelInfoRarityObtained.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelInfoRarityObtained.setPreferredSize(new java.awt.Dimension(721, 50));
        panelInfoRarityObtained.setLayout(new java.awt.GridLayout(1, 3));

        star3InfoPanel.setBackground(new java.awt.Color(102, 51, 0));
        star3InfoPanel.setLayout(new java.awt.GridBagLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("★★★");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        star3InfoPanel.add(jLabel2, gridBagConstraints);

        lblS3Obtained.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblS3Obtained.setForeground(new java.awt.Color(255, 255, 255));
        lblS3Obtained.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblS3Obtained.setText("Obtained : 0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        star3InfoPanel.add(lblS3Obtained, gridBagConstraints);

        panelInfoRarityObtained.add(star3InfoPanel);

        star4InfoPanel.setBackground(new java.awt.Color(204, 204, 204));
        star4InfoPanel.setLayout(new java.awt.GridBagLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("★★★★");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        star4InfoPanel.add(jLabel3, gridBagConstraints);

        lblS4Obtained.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblS4Obtained.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblS4Obtained.setText("Obtained : 0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        star4InfoPanel.add(lblS4Obtained, gridBagConstraints);

        panelInfoRarityObtained.add(star4InfoPanel);

        star5InfoPanel.setBackground(new java.awt.Color(255, 255, 0));
        star5InfoPanel.setLayout(new java.awt.GridBagLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("★★★★★");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        star5InfoPanel.add(jLabel4, gridBagConstraints);

        lblS5Obtained.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblS5Obtained.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblS5Obtained.setText("Obtained : 0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        star5InfoPanel.add(lblS5Obtained, gridBagConstraints);

        panelInfoRarityObtained.add(star5InfoPanel);

        containerCenter.add(panelInfoRarityObtained, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setOpaque(false);

        panelItemsContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 20, 1));
        panelItemsContainer.setOpaque(false);
        panelItemsContainer.setLayout(new java.awt.GridLayout(0, 5));
        jScrollPane1.setViewportView(panelItemsContainer);

        containerCenter.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(containerCenter, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1024, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel closePanel;
    private javax.swing.JPanel containerCenter;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblS3Obtained;
    private javax.swing.JLabel lblS4Obtained;
    private javax.swing.JLabel lblS5Obtained;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panelInfoRarityObtained;
    private javax.swing.JPanel panelItemsContainer;
    private javax.swing.JPanel panelJudul;
    private javax.swing.JPanel star3InfoPanel;
    private javax.swing.JPanel star4InfoPanel;
    private javax.swing.JPanel star5InfoPanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
