package View;

import Model.GachaSystem;
import Model.Item;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import java.awt.Font;

public class PoolDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PoolDialog.class.getName());

    /**
     * Creates new form PoolDialog
     */
    public PoolDialog(java.awt.Frame parent, boolean modal, GachaSystem gachaSystem) {
        super(parent, modal);
        initComponents();
        this.setSize(900, 900);
        this.setPreferredSize(new java.awt.Dimension(900, 900));
        this.setLocationRelativeTo(parent);
        
        muatSemuaAsetPool(gachaSystem);
    }
    
    
    private void muatSemuaAsetPool(GachaSystem gachaSystem) {
        // Pastikan model gachaSystem tidak kosong
        if (gachaSystem == null || gachaSystem.getPool() == null) {
            return;
        }

        // Ambil daftar seluruh item yang ada di pool game kamu
        // Catatan: Sesuaikan nama method .getPool() dengan yang ada di GachaSystem milikmu
        for (Item item : gachaSystem.getPool()) {
            
            // 1. Buat Label baru untuk menampung gambar dan teks
            JLabel lblItem = new JLabel();
            lblItem.setHorizontalAlignment(SwingConstants.CENTER);
//            lblItem.setVerticalTextPosition(SwingConstants.BOTTOM); // Teks di bawah gambar
//            lblItem.setHorizontalTextPosition(SwingConstants.CENTER);
//            lblItem.setFont(new Font("Segoe UI", Font.BOLD, 12));
            
            // Set nama item beserta rating bintangnya sebagai caption teks
//            lblItem.setText(item.getName() + " (" + item.getRarity() + "★)");

            // 2. Muat gambar secara dinamis berdasarkan path tiap item
            try {
                java.net.URL imgURL = getClass().getResource(item.getImagePath());
                if (imgURL != null) {
                    lblItem.setIcon(new ImageIcon(imgURL));
                } else {
                    lblItem.setText("<html><center>" + item.getName() + "<br>[Gambar Hilang]</center></html>");
                }
            } catch (Exception e) {
                System.out.println("Gagal memuat gambar pool: " + e.getMessage());
            }

            // 3. Masukkan label instan ini ke dalam panel utama
            jPanelUtama.add(lblItem);
        }

        // 4. Paksa UI untuk menggambar ulang seluruh komponen baru
        jPanelUtama.revalidate();
        jPanelUtama.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelUtama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        jPanel1.setBackground(new java.awt.Color(153, 204, 0));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DAFTAR ANOMALI");
        jLabel1.setPreferredSize(new java.awt.Dimension(213, 40));
        jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanelUtama.setLayout(new java.awt.GridLayout(3, 4, 5, 5));
        jScrollPane1.setViewportView(jPanelUtama);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
 /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PoolDialog dialog = new PoolDialog(new javax.swing.JFrame(), true,new Model.GachaSystem());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelUtama;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
