/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.Box;

/**
 *
 * @author mw300
 */
public class TestFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TestFrame.class.getName());

    /**
     * Creates new form TestFrame
     */
    public TestFrame() {
        initComponents();

        mainPanel.setOpaque(false);
        BackgroundPanel bgPanel = new BackgroundPanel();

        setContentPane(bgPanel);

        bgPanel.add(mainPanel, java.awt.BorderLayout.CENTER);
        currencyPanel.setBackground(
                new Color(0, 0, 0, 120)
        );

        bgPanel.add(mainPanel, java.awt.BorderLayout.CENTER);
        menuAnomali.setBackground(
                new Color(0, 0, 0, 120)
        );
        bgPanel.add(mainPanel, java.awt.BorderLayout.CENTER);
        menuInventory.setBackground(
                new Color(0, 0, 0, 120)
        );
        bgPanel.add(mainPanel, java.awt.BorderLayout.CENTER);
        menuHistory.setBackground(
                new Color(0, 0, 0, 120)
        );
        bgPanel.add(mainPanel, java.awt.BorderLayout.CENTER);
        menuDetail.setBackground(
                new Color(0, 0, 0, 120)
        );
        bgPanel.add(mainPanel, java.awt.BorderLayout.CENTER);
        pityBg.setBackground(
                new Color(0, 0, 0, 190)
        );

        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bgPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        btnBackContainer = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        pityContainer = new javax.swing.JPanel();
        pityBg = new javax.swing.JPanel();
        lblPity = new javax.swing.JLabel();
        currencyPanel = new javax.swing.JPanel();
        lblTungCoin = new javax.swing.JLabel();
        lblCoinAmount = new javax.swing.JLabel();
        btnAddCoin = new javax.swing.JButton();
        leftPanel = new javax.swing.JPanel();
        menuContainer = new javax.swing.JPanel();
        menuAnomali = new javax.swing.JPanel();
        lblIconBintang = new javax.swing.JLabel();
        lblAnomali = new javax.swing.JLabel();
        menuInventory = new javax.swing.JPanel();
        lblIconInventory = new javax.swing.JLabel();
        lblInventory = new javax.swing.JLabel();
        menuHistory = new javax.swing.JPanel();
        lblIconHistory = new javax.swing.JLabel();
        lblHistory = new javax.swing.JLabel();
        menuDetail = new javax.swing.JPanel();
        lblIconDetail = new javax.swing.JLabel();
        lblDetail = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        footerCenter = new javax.swing.JPanel();
        gachaBtnContainer = new javax.swing.JPanel();
        btnGacha1 = new javax.swing.JButton();
        btnGacha10 = new javax.swing.JButton();
        resetContainer = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();
        dummyLeftPanel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        bannerContainer = new javax.swing.JPanel();
        lblBanner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Anomali Gacha");

        bgPanel.setLayout(new java.awt.BorderLayout());

        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        mainPanel.setFocusable(false);
        mainPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 10, 10));
        topPanel.setOpaque(false);
        topPanel.setPreferredSize(new java.awt.Dimension(791, 60));
        topPanel.setLayout(new java.awt.GridBagLayout());

        btnBackContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        btnBackContainer.setOpaque(false);
        btnBackContainer.setLayout(new java.awt.GridBagLayout());

        btnBack.setBackground(new java.awt.Color(170, 11, 11));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/previous.png"))); // NOI18N
        btnBack.setBorderPainted(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(this::btnBackActionPerformed);
        btnBackContainer.add(btnBack, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        topPanel.add(btnBackContainer, gridBagConstraints);

        pityContainer.setOpaque(false);
        pityContainer.setLayout(new java.awt.GridBagLayout());

        pityBg.setBackground(new java.awt.Color(255, 255, 255));
        pityBg.setPreferredSize(new java.awt.Dimension(85, 25));
        pityBg.setLayout(new java.awt.GridBagLayout());

        lblPity.setBackground(new java.awt.Color(0, 153, 51));
        lblPity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPity.setForeground(new java.awt.Color(255, 255, 255));
        lblPity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPity.setText("Pity : 0 / 90");
        pityBg.add(lblPity, new java.awt.GridBagConstraints());

        pityContainer.add(pityBg, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        topPanel.add(pityContainer, gridBagConstraints);

        currencyPanel.setBackground(new java.awt.Color(255, 255, 255));
        currencyPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 9, 1, 9));
        currencyPanel.setPreferredSize(new java.awt.Dimension(100, 60));
        currencyPanel.setLayout(new java.awt.GridBagLayout());

        lblTungCoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/tungCoin.png"))); // NOI18N
        currencyPanel.add(lblTungCoin, new java.awt.GridBagConstraints());

        lblCoinAmount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCoinAmount.setForeground(new java.awt.Color(255, 255, 255));
        lblCoinAmount.setText("0");
        currencyPanel.add(lblCoinAmount, new java.awt.GridBagConstraints());

        btnAddCoin.setBackground(new java.awt.Color(255, 200, 0));
        btnAddCoin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddCoin.setText("+");
        btnAddCoin.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnAddCoin.setBorderPainted(false);
        btnAddCoin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddCoin.setFocusPainted(false);
        btnAddCoin.setFocusable(false);
        btnAddCoin.setPreferredSize(new java.awt.Dimension(20, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        currencyPanel.add(btnAddCoin, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        topPanel.add(currencyPanel, gridBagConstraints);

        mainPanel.add(topPanel, java.awt.BorderLayout.PAGE_START);

        leftPanel.setOpaque(false);
        leftPanel.setPreferredSize(new java.awt.Dimension(160, 100));
        leftPanel.setLayout(new java.awt.BorderLayout());

        menuContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 50, 1));
        menuContainer.setOpaque(false);
        menuContainer.setLayout(new java.awt.GridBagLayout());

        menuAnomali.setBackground(new java.awt.Color(102, 102, 102));
        menuAnomali.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblIconBintang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/star.png"))); // NOI18N
        lblIconBintang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAnomali.add(lblIconBintang);

        lblAnomali.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAnomali.setForeground(new java.awt.Color(255, 255, 255));
        lblAnomali.setText("Anomali");
        lblAnomali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuAnomali.add(lblAnomali);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        menuContainer.add(menuAnomali, gridBagConstraints);

        menuInventory.setBackground(new java.awt.Color(102, 102, 102));
        menuInventory.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblIconInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/inventory.png"))); // NOI18N
        lblIconInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuInventory.add(lblIconInventory);

        lblInventory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInventory.setForeground(new java.awt.Color(255, 255, 255));
        lblInventory.setText("Inventory");
        lblInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuInventory.add(lblInventory);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        menuContainer.add(menuInventory, gridBagConstraints);

        menuHistory.setBackground(new java.awt.Color(102, 102, 102));
        menuHistory.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblIconHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/history.png"))); // NOI18N
        lblIconHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuHistory.add(lblIconHistory);

        lblHistory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHistory.setForeground(new java.awt.Color(255, 255, 255));
        lblHistory.setText("History");
        lblHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuHistory.add(lblHistory);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        menuContainer.add(menuHistory, gridBagConstraints);

        menuDetail.setBackground(new java.awt.Color(102, 102, 102));
        menuDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDetailMouseClicked(evt);
            }
        });
        menuDetail.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblIconDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/danger (1).png"))); // NOI18N
        lblIconDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuDetail.add(lblIconDetail);

        lblDetail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDetail.setForeground(new java.awt.Color(255, 255, 255));
        lblDetail.setText("Detail");
        lblDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuDetail.add(lblDetail);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        menuContainer.add(menuDetail, gridBagConstraints);

        leftPanel.add(menuContainer, java.awt.BorderLayout.SOUTH);

        mainPanel.add(leftPanel, java.awt.BorderLayout.LINE_START);

        bottomPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 20, 1));
        bottomPanel.setOpaque(false);
        bottomPanel.setLayout(new java.awt.BorderLayout());

        footerCenter.setOpaque(false);
        footerCenter.setLayout(new javax.swing.BoxLayout(footerCenter, javax.swing.BoxLayout.Y_AXIS));

        gachaBtnContainer.setOpaque(false);

        btnGacha1.setBackground(new java.awt.Color(240, 184, 61));
        btnGacha1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGacha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/tungCoin.png"))); // NOI18N
        btnGacha1.setText("1x");
        btnGacha1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGacha1.setFocusPainted(false);
        btnGacha1.setPreferredSize(new java.awt.Dimension(150, 50));
        gachaBtnContainer.add(btnGacha1);

        btnGacha10.setBackground(new java.awt.Color(170, 11, 11));
        btnGacha10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGacha10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/tungCoin.png"))); // NOI18N
        btnGacha10.setText("10x");
        btnGacha10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGacha10.setFocusPainted(false);
        btnGacha10.setPreferredSize(new java.awt.Dimension(150, 50));
        gachaBtnContainer.add(btnGacha10);

        footerCenter.add(gachaBtnContainer);

        bottomPanel.add(footerCenter, java.awt.BorderLayout.CENTER);

        resetContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        resetContainer.setOpaque(false);
        resetContainer.setLayout(new java.awt.BorderLayout());

        btnReset.setBackground(new java.awt.Color(255, 0, 0));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.setFocusPainted(false);
        resetContainer.add(btnReset, java.awt.BorderLayout.PAGE_END);

        bottomPanel.add(resetContainer, java.awt.BorderLayout.EAST);

        dummyLeftPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        dummyLeftPanel.setOpaque(false);
        dummyLeftPanel.setPreferredSize(new java.awt.Dimension(72, 10));
        bottomPanel.add(dummyLeftPanel, java.awt.BorderLayout.WEST);

        mainPanel.add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        rightPanel.setOpaque(false);
        rightPanel.setPreferredSize(new java.awt.Dimension(160, 100));
        mainPanel.add(rightPanel, java.awt.BorderLayout.LINE_END);

        centerPanel.setOpaque(false);
        centerPanel.setLayout(new java.awt.GridBagLayout());

        bannerContainer.setLayout(new java.awt.BorderLayout());

        lblBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/bg.png"))); // NOI18N
        bannerContainer.add(lblBanner, java.awt.BorderLayout.CENTER);

        centerPanel.add(bannerContainer, new java.awt.GridBagConstraints());

        mainPanel.add(centerPanel, java.awt.BorderLayout.CENTER);

        bgPanel.add(mainPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(bgPanel, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(789, 482));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        HalamanAwal h = new HalamanAwal();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void menuDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDetailMouseClicked
        RateDialog dialog = new RateDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_menuDetailMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TestFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bannerContainer;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton btnAddCoin;
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel btnBackContainer;
    private javax.swing.JButton btnGacha1;
    private javax.swing.JButton btnGacha10;
    private javax.swing.JButton btnReset;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel currencyPanel;
    private javax.swing.JPanel dummyLeftPanel;
    private javax.swing.JPanel footerCenter;
    private javax.swing.JPanel gachaBtnContainer;
    private javax.swing.JLabel lblAnomali;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblCoinAmount;
    private javax.swing.JLabel lblDetail;
    private javax.swing.JLabel lblHistory;
    private javax.swing.JLabel lblIconBintang;
    private javax.swing.JLabel lblIconDetail;
    private javax.swing.JLabel lblIconHistory;
    private javax.swing.JLabel lblIconInventory;
    private javax.swing.JLabel lblInventory;
    private javax.swing.JLabel lblPity;
    private javax.swing.JLabel lblTungCoin;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuAnomali;
    private javax.swing.JPanel menuContainer;
    private javax.swing.JPanel menuDetail;
    private javax.swing.JPanel menuHistory;
    private javax.swing.JPanel menuInventory;
    private javax.swing.JPanel pityBg;
    private javax.swing.JPanel pityContainer;
    private javax.swing.JPanel resetContainer;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
